Repository projectsyn/component-vault, pull requests merged in 2022-04, with the labels that each got.

#29 Fix ordering of steps in installation tutorial
  docs/modules/ROOT/pages/tutorials/install.adoc
Labels: documentation

#30 Add vault CLI redirect URL for OIDC login
  docs/modules/ROOT/pages/tutorials/install.adoc
Labels: documentation

#31 Fix tenant name reclass references
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/tutorials/install.adoc
Labels: bug

#28 Rename the helm chart release_name variable for Kapitan to name
  class/vault.yml
Labels: dependency

#32 Fix backup ServiceAccount missing
  component/backup.jsonnet
Labels: bug

#33 Fix backup tmpfile permissions on OCP
  component/backup.jsonnet
  tests/defaults.yml
  tests/golden/defaults/vault/vault/30_backup/31_schedule.yaml
  tests/golden/defaults/vault/vault/30_backup/32_backup.yaml
Labels: bug

#35 Start vault agent and let it finish before attempting a backup
  component/backup.jsonnet
  tests/golden/defaults/vault/vault/30_backup/32_backup.yaml
Labels: bug

#14 Update dependency docker.io/banzaicloud/bank-vaults to v1.15.2
  class/defaults.yml
  tests/golden/defaults/vault/vault/10_vault/vault/templates/server-statefulset.yaml
  tests/golden/defaults/vault/vault/22_config.yaml
Labels: dependency

#36 Update dependency docker.io/vault to v1.9.4
  class/defaults.yml
  tests/golden/defaults/vault/vault/10_vault/vault/templates/server-statefulset.yaml
  tests/golden/defaults/vault/vault/30_backup/32_backup.yaml
Labels: dependency
