Repository projectsyn/component-vault, pull requests merged in 2025-06, with the labels that each got.

#95 Remove Go unit tests for component
  .cruft.json
  .github/workflows/test.yaml
  Makefile
  tests/go.mod
  tests/go.sum
  tests/unit/defaults_test.go
Labels: ignore

#81 Update ghcr.io/bank-vaults/bank-vaults Docker tag to v1.31.3
  class/defaults.yml
  tests/golden/defaults/vault/vault/10_vault/vault/templates/server-statefulset.yaml
  tests/golden/defaults/vault/vault/22_config.yaml
  tests/golden/openshift/vault/vault/10_vault/vault/templates/server-statefulset.yaml
  tests/golden/openshift/vault/vault/22_config.yaml
Labels: dependency

#83 Update docker.io/hashicorp/vault Docker tag to v1.19.5
  class/defaults.yml
  tests/golden/defaults/vault/vault/10_vault/vault/templates/server-statefulset.yaml
  tests/golden/defaults/vault/vault/30_backup/32_backup.yaml
  tests/golden/openshift/vault/vault/10_vault/vault/templates/server-statefulset.yaml
  tests/golden/openshift/vault/vault/30_backup/32_backup.yaml
Labels: dependency, bump:minor
